### ISSUE TITLE
Hyperate BPM dropping to 0 since update

### ISSUE THREAD

**Issue by ImTyr0** [VolcanicArts/VRCOSC#101]
Hyperate bpm since update has been frequently displaying 0 bpm between updates.
It still displays actual, accurate readings, but often shows 0 for a few seconds.

**Comment by VolcanicArts** [comment]
If any heartrate module doesn't receive a value for more than 10 seconds it will assume your heartrate monitor has turned off. I can increase the timeout

**Comment by ImTyr0** [comment]
I just counted 6 seconds of no updates and then it displayed 0 bpm. So I'm not sure if 10 second timeout is the issue here.
Just for clarification I have used this feature for a few months and only recently become an issue,

**Comment by VolcanicArts** [comment]
Which Heartrate module are you using

**Comment by ImTyr0** [comment]
Hyperate

**Comment by ImTyr0** [comment]
Actually it could be timeout, assuming that the 10 second thing is a new feature.
I use smoothing so the few seconds of it updating with smoothing and not getting an actual new value could be triggering the timout.

**Comment by VolcanicArts** [comment]
The timeout has been present the entire time the HypeRate module has existed. It's entirely possible that your heartrate is stable enough that it won't change for 10 seconds

**Comment by ImTyr0** [comment]
Would there be any way to be able to edit the timeout variable manually, or wait for an official update?

**Comment by VolcanicArts** [comment]
The timeout is embedded into the Heartrate modules, so you'd have to wait. There will most likely be one this weekend

**Comment by ImTyr0** [comment]
Okay, thank you for your time ^-^
