### ISSUE TITLE
Module initialization exception is not logged

### ISSUE THREAD

**Issue by DJDavid98** [VolcanicArts/VRCOSC#114]
In the following lines:

https://github.com/VolcanicArts/VRCOSC/blob/bc6f60e65abf4571de1e4af78af54629d556782b/VRCOSC.Game/Managers/ModuleManager.cs#L125-L128

the module initialization exception is caught, but as a result it will be absent from any of the logs, making root cause analysis and fixing of the underlying issue difficult.

**Comment by VolcanicArts** [comment]
Good catch. I'll relog the error same as done in the base module.
