### ISSUE TITLE
Feature Request: automatically trigger AFK after X minutes of inactivity

### ISSUE THREAD

**Issue by Wasmachineman-NL** [VolcanicArts/VRCOSC#116]
Something from my Metastruct Gmod days: auto-AFK. After two minutes of inactivity or so, it'll show players you're AFK in the scoreboard.

Would be nice if this could be a thing in VRCOSC, as it would give me reason to actually run it in the background while i'm doing shit IRL.

**Comment by VolcanicArts** [comment]
AFK Display uses VRChat's AFK avatar parameter to detect when you've got AFK. If VRChat doesn't detect you as AFK, then neither will VRCOSC

**Comment by Wasmachineman-NL** [comment]
> AFK Display uses VRChat's AFK avatar parameter to detect when you've got AFK. If VRChat doesn't detect you as AFK, then neither will VRCOSC

So I suppose adding an internal timer to VRCOSC is out of the question?

**Comment by VolcanicArts** [comment]
It wouldn't make any sense to do that since it's designed to show how long you've been AFK in VRChat. What would the internal timer even reset on?

**Comment by Wasmachineman-NL** [comment]
> It wouldn't make any sense to do that since it's designed to show how long you've been AFK in VRChat. What would the internal timer even reset on?

Reset on movement in VRChat itself, i.e when you start playing again.

**Comment by VolcanicArts** [comment]
If you're playing on desktop I can see how the AFK parameter wouldn't enable when you just tab out the game, but you may not move for 10 mins with or without being AFK depending on how you're playing the game

**Comment by Wasmachineman-NL** [comment]
> If you're playing on desktop I can see how the AFK parameter wouldn't enable when you just tab out the game, but you may not move for 10 mins with or without being AFK depending on how you're playing the game

It definitely is more something for desktop users like yours truly.

**Comment by DJDavid98** [comment]
There is a desktop keybind to trigger AFK mode manually, the End key: https://docs.vrchat.com/docs/keyboard-and-mouse

You just have to press that key when you go AFK and press it again when you come back. It is not exactly what you are asking for but it is an option that already exists and should integrate with the existing AFK detection used by VRCOSC.

**Comment by Wasmachineman-NL** [comment]
While true, I would still love it if VRCOSC automatically could trigger it.

**Comment by VolcanicArts** [comment]
I don't think I'll be implementing anything else. VRCOSC is designed around using VRChat's data so making it more generic to just detect when you're not at your PC seems out of scope. There's an argument for checking in-game movement but you could just not move and still be present as I mentioned previously.

**Comment by DJDavid98** [comment]
This functionality could be implemented by someone as a custom module, physbones + self-only senders & receivers can be used for motion detection and reporting AFK status from an in-game parameter. If someone wants to implement it, the possibilities are there. It certainly seems a bit out of scope for inclusion in the app itself.
