### ISSUE TITLE
Chatbox text not working at all

### ISSUE THREAD

**Issue by TotallyNotVoidTTV** [VolcanicArts/VRCOSC#118]
![image](https://github.com/VolcanicArts/VRCOSC/assets/136023766/b90bbc59-a93e-4c72-935a-8ed91b7ce35d)

doesnt show up in game at all

**Comment by VolcanicArts** [comment]
Can you go through this section of the FAQ please: https://github.com/VolcanicArts/VRCOSC/wiki/FAQ#things-to-try-first

**Comment by TotallyNotVoidTTV** [comment]
so i changed worlds it hasnt fixed it do i restart my pc

**Comment by VolcanicArts** [comment]
Go through the section

**Comment by VolcanicArts** [comment]
If the things to try first doesn't work I'd suggest you join the Discord server to more easily get help by opening a support thread
