### ISSUE TITLE
clock module has missing parameters

### ISSUE THREAD

**Issue by hoshimi-draws** [VolcanicArts/VRCOSC#122]
![VRCOSC_5HOHRGdUby](https://github.com/VolcanicArts/VRCOSC/assets/84279282/766dec12-0b4f-4d8c-8608-9bb6c167fa9f)

should have "VRCOSC/Clock/Period" as an output
also 12/24 hour switch does nothing and doesnt even save in the module .json

ps- sorry for lack of tags, or link to my attempt at making a patch- prematurely hit enter

**Comment by VolcanicArts** [comment]
It's not a missing parameter, and period was never meant to be sent. The 12/24 hour switch is purely for ChatBox use as the watch prefab requires the time be sent in 12 hour mode
