### ISSUE TITLE
Media module not showing album name?

### ISSUE THREAD

**Issue by Wasmachineman-NL** [VolcanicArts/VRCOSC#134]
This a bug or something? Tried it with the Cisfinitum track in question, and some of the Genshin Impact Soundtrack tracks. Latest version of VLC.
![Knipsel](https://github.com/VolcanicArts/VRCOSC/assets/35110496/b5235680-e073-469c-9d80-2b27e602146a)

**Comment by VolcanicArts** [comment]
VLC doesn't interact with Windows media at all so I don't know how VRCOSC is receiving that information. I tried to find a plugin that could allow VLC to send the required data but one doesn't seem to exist
