### ISSUE TITLE
VRCOSC crashing VRChat with HR option turned on

### ISSUE THREAD

**Issue by ericohtwo** [VolcanicArts/VRCOSC#142]
I use this app for basic heartrate display via Pulsoid, but every time I do so, VRChat hard crashes after having been active for a while (10-20 minutes, varies) and then proceeds to not open anymore until I restart SteamVR.

What could this be? I have uninstalled and reinstalled to latest version but I'm still getting crashes like those. Could it simply just be some sort of background software issue?

**Comment by VolcanicArts** [comment]
Can you join the [Discord Server](https://discord.gg/vj4brHyvT5) and create a support post in the support forums and send your `runtime.log` file from `%appdata%/vrcosc/logs` as soon as VRCOSC crashes please?
