### ISSUE TITLE
GPU VRAM is not showing on AMD Graphics Cards

### ISSUE THREAD

**Issue by jebuzjack** [VolcanicArts/VRCOSC#155]
Not sure if anyone elese has this issue but only the VRAM does not display for me when using an AMD GPU. Everything else works but that.

Current Setup:

Ryzen 7 7800X3D
RX 7800 XT
Windows 11

**Comment by VolcanicArts** [comment]
Please join the [Discord Server](https://discord.gg/vj4brHyvT5) and open a support thread and post your generated log from [LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/tag/v0.9.2)
