### ISSUE TITLE
Latest version of VRChat will crash VRCOSC

### ISSUE THREAD

**Issue by FleuryK** [VolcanicArts/VRCOSC#156]
Hello,

With the latest version of VRChat, version 2023.4.2 1388, VRCOSC crash instantly, and it no longer works.

Will there be an update?

Cordially.

**Comment by VolcanicArts** [comment]
Can you join the [Discord Server](https://discord.gg/vj4brHyvT5) and make a support thread and post your `runtime.log` file from `%appdata%/vrcosc/logs` please?
