### ISSUE TITLE
OSC Query is not used

### ISSUE THREAD

**Issue by SkySpnc** [VolcanicArts/VRCOSC#157]
OSC Query is not used which causes an exception to throw when being used with other OSC apps - a good example is VRCFT which also has yet to migrate.

**Comment by VolcanicArts** [comment]
OSCQuery is available in V2 and won't be added to the current version of the app. Please use the router if you want to use any other OSC apps alongside VRCOSC

**Comment by SkySpnc** [comment]
v2 is not in pre-release on Github, nor is it a seperate public repo.
discord is not a file hosting platform and should not be used as one. especially one with closed source code, that's dodgy.

**Comment by VolcanicArts** [comment]
The V2 code is open source and available on the V2 branch

**Comment by SkySpnc** [comment]
ah, missed the branch. my bad. is there a pre-compiled binary available for this?

**Comment by VolcanicArts** [comment]
It's available inside the ZIP that's provided in the Discord server, along with the nuget package for developing modules using the SDK. I'll consider doing pre-releases on GitHub once the automatic updater has been implemented into V2
