### ISSUE TITLE
Add wikipage for Gesture Extensions

### ISSUE THREAD

**Issue by Sirkku** [VolcanicArts/VRCOSC#159]
I've tried finding information how and which gestures this module detects on this wiki and on the discord and haven't found any. I've looked at the source and wrote up a small note that should be useful for people trying to implement it in their avatar (especially the table).

[VRCOSC GestureExtensions Wikipage Proposal.md](https://github.com/VolcanicArts/VRCOSC/files/14348334/VRCOSC.GestureExtensions.Wikipage.Proposal.md)

I am confident this should cover the entirety of the plugin, but please kindly correct my english.

**Comment by VolcanicArts** [comment]
Sure.
https://github.com/VolcanicArts/VRCOSC/wiki/Gesture-Extensions
