### ISSUE TITLE
Your Windows has an Image Element with a problem

### ISSUE THREAD

**Issue by itzRykon** [VolcanicArts/VRCOSC#163]
![image](https://github.com/VolcanicArts/VRCOSC/assets/70638923/26fbfc95-2be0-4b2a-8ecb-c332d66e39a2)

i get this error the whole time i start it, how to fix it?

**Comment by VolcanicArts** [comment]
I don't do anything with Python. Are you mistaking this app for another?

**Comment by itzRykon** [comment]
oh wait a minute i had a second task open where i searched different osc tools lol, my bad
