### ISSUE TITLE
VRCOSC will crash if idle too long/Pi Shock API latency

### ISSUE THREAD

**Issue by candygamer-YT** [VolcanicArts/VRCOSC#165]
I've noticed through out all my VR sessions VRCOSC constantly crashes every 1 to 2 hours especially when it's been idle for too long. 
(aka doing nothing)

And even while not in use in VR like referencing it for unity work. (Fresh windows start up.)
It also will freeze/crash and exiting via the icon on the task bar and alt+F4 doesn't even work during a freeze 
(I have to kill it via task manager)

If you have any logs in any place or any way for me to test what it could be that's causing it let me know! 
But it's very infuriating to use this application and it's persisted even on a fresh install of windows.

Also when calling to the PiShock API VRCOSC takes an extra 1-2 seconds before it actually sends the API request after parameters are changed. (This should be instant)

It was instant when I first used it but it no longer is after 4 or 5 uses.

**Comment by VolcanicArts** [comment]
Please join the Discord server and open a support post with your `%appdata%/vrcosc/logs/runtime.log` file after a crash
