### ISSUE TITLE
Memory Leak issue

### ISSUE THREAD

**Issue by SalbugVR** [VolcanicArts/VRCOSC#166]
When running VRCOSC for a while, it seems to cascade into memory leak issues.

![Taskmgr_K4hXw2hpqe](https://github.com/user-attachments/assets/206933ea-0a11-4390-a040-05efc705a61e)

**Comment by VolcanicArts** [comment]
It's not a memory leak. You've got a VRChat log file that's oversized. Delete your VRChat logs and restart VRCOSC and that should fix it.
