### ISSUE TITLE
ram leak?

### ISSUE THREAD

**Issue by FIR-305** [VolcanicArts/VRCOSC#167]
I know there was a post that was said to be solved about this a while back in like jun 2022, but the latest version of the software on a windows 11 x64 system is still giving me a leak it will go from like 800mb of ram used to like 7,000+ within a few seconds of the software running I can give my system spec fully if you want but I cant think of whats causing this issue.

**Comment by VolcanicArts** [comment]
Delete your VRChat logs. The app loads the latest log into memory and the latest log is likely oversized
