### ISSUE TITLE
new update breaks router

### ISSUE THREAD

**Issue by cadergator10** [VolcanicArts/VRCOSC#169]
when using new router (only recieve port now), whenever turned on, face tracking goes crazy along with haptics. both normal again when turning vrcosc off again

**Comment by VolcanicArts** [comment]
You don't need to use the router anymore.
VRCOSC now uses OSCQuery.
VRCFT uses OSCQuery. Make sure it's up-to-date and the ports are set to default.
BHaptics can work without OSCQuery as VRCOSC and VRCFT use OSCQuery
