### ISSUE TITLE
new update breaks all settings

### ISSUE THREAD

**Issue by sophienix** [VolcanicArts/VRCOSC#170]
is there a way to fix this i cant seem to import my old settings i dont to have to restart from scratch is there some way to convert old settings to new version ?

**Comment by VolcanicArts** [comment]
No. V1 files are incompatible with V2. You will need to remake your configs or ask in the Discord server for help with making them

**Comment by sophienix** [comment]
that is fine im already done with most of it just need help with voice commands it wont download models

**Comment by VolcanicArts** [comment]
Go into the speech settings of the app and click the "Auto Install Model" button
