### ISSUE TITLE
v2 startup location error

### ISSUE THREAD

**Issue by BAKAOLC** [VolcanicArts/VRCOSC#171]
The v2 version automatically centers the window on startup, but it doesn't work correctly on my computer!
It moves the position between my two screens on startup and hides half of the window at the bottom of the screen
Computer resolution: dual monitors (3840x2160 each)
DPI: 200% for both screens
VRCOSC version: 2024.1223.0

**Comment by VolcanicArts** [comment]
This will be fixed in the next update
