### ISSUE TITLE
add window os media to chatbox

### ISSUE THREAD

**Issue by ProjecttFrostt** [VolcanicArts/VRCOSC#46]

**Comment by VolcanicArts** [comment]
This is an idea currently on my to-do list. Unfortunately there have been struggles with the way Windows exposes the OS media to a project using .NET6.

**Comment by VolcanicArts** [comment]
This issue got me looking into it again and I believe I've found a fix. Targeting the .NET6 version for Windows 11 seems to work, but I'll need to do more testing to make sure this doesn't break anything else.

For now I have got it working and can read the data.

**Comment by VolcanicArts** [comment]
The Spotify module will be deprecated in the next release in favour of Media as I've got all the controls from Spotify and more. Your original suggestion of the Media module having ChatBox functionality has been implemented.

Thanks for using VRCOSC.

**Comment by ProjecttFrostt** [comment]
walking W

**Comment by ProjecttFrostt** [comment]
cant wait for the update for it then
