### ISSUE TITLE
Is it possible to have media and hardware stats both work in the chat?

### ISSUE THREAD

**Issue by ProjecttFrostt** [VolcanicArts/VRCOSC#49]

**Comment by VolcanicArts** [comment]
Yes.

If you turn off "Continuous Show" in the Media module's settings, Media will override whenever a new song plays and return control back to Hardware Stats after the time specified in "Display Period" also in the Media module's settings.

If you decide you want to show the time and keep "Continuous Show" on, then pausing the song will cause Hardware Stats to once again have control over the ChatBox.
