### ISSUE TITLE
Multiple Modules

### ISSUE THREAD

**Issue by XenoxUSser** [VolcanicArts/VRCOSC#64]
Is there a Way to display like clock and media at once without them interrupting the other?

**Comment by VolcanicArts** [comment]
The way the ChatBox system works is that you can either show certain modules every X seconds for Y seconds, or always show the module (with multiple always modules using their priority. See the latest release notes for a longer explanation).

To show both clock and media, you can set the media module to have a mode of `always`, and the clock module to have a mode of `timed`, as well as a timer of 10 seconds, and a length of 5 seconds. This will alternate between the clock module and the media module every 5 seconds.

If you want to show both modules in the ChatBox at the same time, that's not possible. The watch prefab hooks up to the clock module so you can show your local time that way as a compromise if you want to constantly show both modules' data.
