### ISSUE TITLE
Crashes after closing the console thing (incoming/outgoing)

### ISSUE THREAD

**Issue by Progamer75303** [VolcanicArts/VRCOSC#67]
The Program sometimes crashes after i closed the console thing (incoming/outgoing)
![image](https://user-images.githubusercontent.com/78344868/206813200-c9598401-276b-4287-a90b-09a902d43b2e.png)
![image](https://user-images.githubusercontent.com/78344868/206813290-88a3e76e-f9b5-453f-8eb0-959c6a9f0d16.png)

**Comment by VolcanicArts** [comment]
Can you send your runtime.log text file located here `C:\Users\USERNAME\AppData\Roaming\VRCOSC\logs`, please?

**Comment by Progamer75303** [comment]
[runtime.log](https://github.com/VolcanicArts/VRCOSC/files/10198788/runtime.log)

**Comment by Progamer75303** [comment]
and i just found out that it sometimes randomly crashes but when i close this menu it nearly always happens

**Comment by VolcanicArts** [comment]
Cheers. I have a suspicion of what's wrong. I'll investigate tomorrow

**Comment by VolcanicArts** [comment]
I managed to reproduce your issue and this will be solved in the next update, probably sometime this weekend.

Was just a crash regression since I changed to the new ChatBox system
