### ISSUE TITLE
When playing music with Groove-Music it doesnt display the time

### ISSUE THREAD

**Issue by Progamer75303** [VolcanicArts/VRCOSC#69]
When playing music with Groove-Music it doesnt display the time
![image](https://user-images.githubusercontent.com/78344868/206856879-d158dd1d-4db0-4a92-9991-fe9808e997ca.png)

**Comment by VolcanicArts** [comment]
This is a limitation of Groove music. From what I've seen it doesn't expose any details to Windows Media

**Comment by Progamer75303** [comment]
ok so it is a windows thing and doesnt work?

**Comment by VolcanicArts** [comment]
Yup. I checked on my own machine using VRCOSC as well as another known working app. Neither could find any data to read
