### ISSUE TITLE
VirusTotal Threat Count pretty high

### ISSUE THREAD

**Issue by GhostJumper** [VolcanicArts/VRCOSC#95]
[VirusTotal](https://www.virustotal.com/gui/file/2fddfd5e9bed3bb2563e983aab7785f863c7d285ad9bb18b41f9ef6d7e56b5b0?nocache=1) seems to be pretty certain that the [newest executable](https://github.com/VolcanicArts/VRCOSC/releases/tag/2023.309.1) might pose a threat.

Is there a specific pattern in the code that causes this threat detection?

**Comment by VolcanicArts** [comment]
Probably the number of embedded DLLs for things like face tracking to work
